<?
$aMenuLinks = Array(
    Array(
        "Доска объявлений",
        "/ads/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Компании",
        "/companies/",
        Array(),
        Array("data-open"=>"company-menu"),
        ""
    ),
    Array(
        "О проекте",
        "/about/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Сотрудничество",
        "/partnership/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Блог",
        "/blog/",
        Array(),
        Array(),
        ""
    )
);
?>