<?
$aMenuLinks = array(
    array(
        "Профиль",
        "/personal/",
        array(),
        array(),
        ""
    ),
    array(
        "Избранное",
        "/personal/favorite/",
        array(),
        array(),
        ""
    ),
    array(
        "Добавить обьявление ",
        "/personal/announcement/",
        array(),
        array(),
        ""
    ),
    array(
        "Мои обьявления",
        "/personal/ads-list/",
        array(),
        array(),
        ""
    ),
    array(
        "Выход",
        "/?logout=yes",
        array(),
        array(),
        ""
    )
);
?>