<?
$aMenuLinks = Array(
    Array(
        "Оголошення",
        "/ua/ads/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Спільноти",
        "/ua/community/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Про проект",
        "/ua/about/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Співпраця",
        "/ua/partnership/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Блог",
        "/ua/blog/",
        Array(),
        Array(),
        ""
    )
);
?>
