<?
$aMenuLinks = Array(
    Array(
        "Дошка оголошень",
        "/ua/ads/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Компанії",
        "/ua/companies/",
        Array(),
        Array("data-open"=>"company-menu"),
        ""
    ),
    Array(
        "Про проєкт",
        "/ua/about/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Співпраця",
        "/ua/partnership/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Блог",
        "/ua/blog/",
        Array(),
        Array(),
        ""
    )
);
?>